apiVersion: v1
kind: Service
metadata:
  name: static-nfspvc-recyclepv
  labels:
    name: app
    # type: nfs 
    env: prod
    release: v1.0

spec:
  type: NodePort
  selector:
    app: jenkins-deploy
    env: prod
    release: v1.0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080