apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nfs-recyclepv
  labels:
    name: app
    env: prod
    release: v1.0

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      # terminationGracePeriodSeconds: 60

