apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-nginx-deploy
  labels:
    app: nginx-app
    env: prod
    release: v1.0

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
      env: prod 
      release: v1.0

  template:
    metadata:
      name: nfs-nginx-deploy
      labels:
        app: nginx-app
        env: prod
        release: v1.0

    spec:
      containers:
      - name: write-app
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/log

      - name: serve-app
        image: nginx:1.27.4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: nfs-volume
            mountPath: /usr/share/nginx/html
      volumes:  
      - name: nfs-volume
        nfs:
          # server: nfs-server.default.svc.cluster.local
          server: 192.168.0.126
          path: /var/nfs
