apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport-svc
  labels:
    app:  nodeportsvc

spec:
  selector: 
    app: cicd-server
    env: prod+
    release: v1.0

  ports:
    - name: cicd-port
      port: 80
      targetPort: 8080 
      protocol: TCP
  type: NodePort