apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx
    environment: production
    
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
      
  template:
    metadata:
      name: nginx-demo
      labels:
        app: nginx
        environment: production
        
    spec:
      containers:
      - name: write-container
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true;do echo `date`: $POD_IP: $POD_NAME: $CPU_LIMIT: $MEMORY_LIMIT | tee -a /var/log/index.html >> /proc/1/fd/1; sleep 10;done"]
        resources: 
          limits:
            memory: "250Mi" #250MB
            cpu: "250m" #20% of a single core
          requests:
            memory: "100Mi" #100MB
            cpu: "100m" #10% of a single core
        env:
          - name: CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: write-container
                resource: limits.cpu
          - name: MEMORY_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: write-container
                resource: limits.memory
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          # and more environment variables can be added here...

        volumeMounts:
          - name: shared-data
            mountPath: /var/log
      volumes:
        - name: shared-data
          downwardAPI:
            items:
              - path: "index.html"
                fieldRef:
                  fieldPath: metadata.name
