apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-multicontainer-rc
        env: prod
        release: v1.0
    spec:
      containers:
      - name: write-app
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
        volumeMounts:
        - name: rc-shared-volume
          mountPath: /var/log

      - name: server-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: rc-shared-volume
          mountPath: /usr/share/nginx/html

      volumes:
      - name: rc-shared-volume
        emptyDir: {}

# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: nginx-rc
# spec:
#   replicas: 3
#   selector:
#     app: nginx-multicontainer-rc
#   template:
#     metadata:
#       labels:
#         app: nginx-multicontainer-rc
#         env: prod
#         release: v1.0
#     spec:
#       containers:
#       - name: write-app
#         image: alpine
#         command: ["/bin/sh"]
#         args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
#         volumeMounts:
#         - name: rc-shared-volume
#           mountPath: /var/log
#       - name: server-app
#         image: nginx:latest
#         ports:
#         - containerPort: 80
#         volumeMounts:
#         - name: rc-shared-volume
#           mountPath: /usr/share/nginx/html
#       volumes:
#       - name: rc-shared-volume
#         emptyDir: {}