apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    app: nginx-rc
    type: rc-prod

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-rc
        
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "300Mi"
            cpu: "0.2"
          requests:
            memory: "200Mi"
            cpu: "0.1"