apiVersion: v1 #apiVersion of svc
kind: Service #kind of svc
metadata: #metadata of svc - name, labels
  name: extname-svc
  labels:
    app: nginx-app
    env: prod
    release: v1.0

spec: #spec of svc
  type: ExternalName #type of svc
  externalName: www.hexrfactory.com
  # ports: #ports of svc (are highly optional)
  #   - name: http
  #     port: 80
  #     targetPort: 80
  #     protocol: TCP
