apiVersion: v1 
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: app
    env: prod
    release: v1.0

spec:
containers:
    - name: app
      image: nginx:1.7.9
      ports:
        - containerPort: 80
          hostPort: 8090
          protocol: TCP
      volumeMounts:
        - name: static-pvc-hostpath 
          mountPath: /usr/share/nginx/html
volumes:
    - name: static-pvc-hostpath
      persistentVolumeClaim:
        claimName: static-pvc-hostpath