apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj1
spec:
  schedule: "*/2 * * * *"
  # timezone: "Asia/Kolkata"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 10 
      restartPolicy: OnFailure
      template:
        spec:
          containers:
              image: ubuntu:latest
              args:
                - /bin/bash
                - -c
                - date; echo Welcome to cronJob
