apiVersion: v1 #apiVersion of svc
kind: Service #kind of svc
metadata: #metadata of svc - name, labels
  name: extip-svc
  labels:
    app: nginx-app
    env: prod
    release: v1.0

spec: #spec of svc
  ports: #ports of svc
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

  selector: #selector of svc to match pods usind identica labels
    app: nginx-app
    env: prod
    release: v1.0

  # type: ExternalIP #type of svc
  externalIPs: #externalIPs of svc to be used to access PODs
    - 192.168.0.222
