apiVersion: v1
kind: Pod #object
metadata:
  name: initcontainer-pod
  labels:
    name: initcontainer-pod
    app: nginx
    type: web
    object: initcontainer
spec:
  initContainers:
    - name: initcontainer
      image: alpine:latest
      command: 
        - wget
        - "-O" #output
        - "/var/tmp/index.html" #working directory
        - https://github.com/rithishsammhexr/initcontainers-test/blob/main/index.html?raw=true #to get raw .html content from repo
      volumeMounts:
        - name: initcontainer-pod-vol
          mountPath: /var/tmp
  containers:
    - name: serve-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
          hostPort: 8091
          #hostIP: #host IP address gets opt in by default, no need to specify.
      volumeMounts:
        - name: initcontainer-pod-vol
          mountPath: /usr/share/nginx/html #these containers will run first during pod initialization and will be stopped after pod creation
  volumes:
    - name: initcontainer-pod-vol
      emptyDir: {}