apiVersion: v1
kind: Pod
metadata:
  name: podapp-nginx
  labels:
    app: podapp-nginx
    env: prod
    image: nginx
spec:
  containers:
    - name: podapp-nginx
      image: nginx:latest
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      env:
        - name: DB_USER
          value: "root"
      resources:
        limits: #max limit
          cpu: "700m" #can be in percentage%/micron-mi/core-numberValue
          memory: "500Mi" #also for Ki for Kilobytes, Mi for Megabytes, Gi for Gigabytes, Ti for Terabytes
        requests: #min limit
          cpu: "200m"
          memory: "200Mi"
      volumeMounts:
        - name: podapp-vol
          mountPath: /usr/share/nginx/html #mounting this one to emptyDir{} + whatever data written here will be appear -> also in emptyDir{}
  volumes:
    - name: podapp-vol
      emptyDir: {} #volume of Path's container volume gets mounted to emptyDir{} a.k.s HostVolume