apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
  labels:
    name: pv-pod
    env: prod
    release: v1.0
    
spec: 
  containers:
  - name: nfs-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: nfs-pv
      mountPath: /usr/share/nginx/html

  volumes:
  - name: nfs-pv
    persistentVolumeClaim:
      claimName: static-nfs-pv