apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-nfs-pv
  labels:
    name: app
    # type: nfs
    env: prod
    release: v1.0
    
spec:
  storageClassName: nfs
  capacity:
    storage: 3Gi #<Size> of availeble nfs server, check that using `df -h` 
  accessModes: #refer docs that which accessModes are allowed for nfs
    - ReadWriteMany #ReadWriteOnce if you want to use it for single pod, Many if multiple pods
  nfs:
    server: 192.168.0.126
    path: /var/nfs/nfspv
  # volumeMode: Filesystem
  # persistentVolumeReclaimPolicy: Recycle
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1

  #------------------------------------------------------------------

  # storageClassName: slow
  # capacity:
  #   storage: 1Gi
  # volumeMode: Filesystem
  # accessModes:
  #   - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2

#------------------------------------------------------------------

  # capacity:
  #   storage: <Size>
  # volumeMode: Filesystem
  # accessModes:
  #   - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2


#------------------------------------------------------------------