apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx-ds
    env: prod
    release: v1.0

spec:
  selector:
    matchLabels:
      app: nginx-ds
      env: prod
      release: v1.0

  template:
    metadata:
      labels:
        app: nginx-ds
        env: prod
        release: v1.0

    spec:
      containers:
      - name: write-app
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/index.html; sleep 10; done"]
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: deploy-shared-volume
          mountPath: /var/log

      - name: serve-app
        image: nginx:1.27.4
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: deploy-shared-volume
            mountPath: /usr/share/nginx/html
            
      volumes:  
      - name: deploy-shared-volume
        emptyDir: {}