apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-hostpath
  labels:
    type: hostpath
    env: prod
    release: v1.0

spec:
  terminationGracePeriodSeconds: 60
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/tmp/nginx-data"
    type: DirectoryOrCreate



# spec:
#   capacity:
#     storage: <Size>
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: slow
#   mountOptions:
#     - hard
#     - nfsvers=4.1
#   nfs:
#     path: /tmp
#     server: 172.17.0.2
