apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-hostpath
spec:
  terminationGracePeriodSeconds: 60
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi