apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
  labels:
    app: nginx-ds
    env: prod
    release: v1.0
    
spec:
  selector:
    matchLabels:
      app: nginx-ds
      env: prod
      release: v1.0

  template:
    metadata:
      labels:
        app: nginx-ds
        env: prod
        release: v1.0

    spec:
      containers:
      - name: write-app
        image: alpine
        command: ["/bin/sh", "-c", "echo Hello World > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: ds-shared-volume
          mountPath: /usr/share/nginx/html

      - name: serve-app
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ds-shared-volume
          mountPath: /usr/share/nginx/html
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"

      volumes:
      - name: ds-shared-volume
        emptyDir: {}