apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
  labels:
    app: clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-app
    #purposefully declaring only one label - labels has to be identical and match with atleast one parameter of label. 
  ports:
    - protocol: TCP
      port: 80